name: Optimize images & upgrade HTML

on:
  push:
    branches: [main]
    paths:
      - "images/**"
      - "**/*.html"
      - "scripts/**"
      - "package.json"
      - "package-lock.json"
  workflow_dispatch:

jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: |
          npm ci || npm i --no-audit --no-fund

      - name: Generate AVIF/WebP + PNGs
        run: npm run optimize:images

      - name: Rewrite HTML to <picture>
        run: npm run upgrade:html

      - name: Create PR with optimizations (if any)
        uses: peter-evans/create-pull-request@v6
        with:
          title: "chore: optimize images and upgrade HTML to <picture>"
          commit-message: "chore: generate AVIF/WebP variants and rewrite <img> to <picture>"
          branch-suffix: timestamp
          labels: optimization
